-- Este archivo fue vaciado el 22/09/2026.
-- La migración 20260922060000_phase_0_foundation.sql es la fuente
-- de verdad del esquema de Fase 0.
-- Este archivo se conserva vacío para no alterar el orden cronológico
-- de migraciones en Supabase.
-- No ejecutar: no define ningún objeto de base de datos.
